INFO Beginning test at Sun Jan 20 12:55:17 2013
INFO Capabilities are: GENERIC, OSX
INFO sys.platform = darwin
INFO pyglet.version = 1.2alpha1
INFO Reading test plan from tests/plan.txt
INFO --- test (1/134) top.IMPORT
INFO Begin unit tests for top.IMPORT
INFO 27 tests run
INFO --- test (2/134) app.EVENT_LOOP
INFO Begin unit tests for app.EVENT_LOOP
ERROR Failure in app.EVENT_LOOP
ERROR Traceback (most recent call last):
  File "tests/../tests/app/EVENT_LOOP.py", line 54, in test_1_5
    self.t_scheduled(1, 5, 0)
  File "tests/../tests/app/EVENT_LOOP.py", line 48, in t_scheduled
    pyglet.app.run()
  File "tests/../pyglet/app/__init__.py", line 123, in run
    event_loop.run()
  File "tests/../pyglet/app/base.py", line 135, in run
    self._run_estimated()
  File "tests/../pyglet/app/base.py", line 164, in _run_estimated
    timeout = self.idle()
  File "tests/../pyglet/app/base.py", line 273, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "tests/../pyglet/clock.py", line 309, in call_scheduled_functions
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "tests/../tests/app/EVENT_LOOP.py", line 37, in f
    self.assertAlmostEqual(dt, interval, places=2)
AssertionError: 2.1518380641937256 != 1 within 2 places

INFO 8 tests run
INFO --- test (3/134) graphics.GRAPHICS_ALLOCATION
INFO Begin unit tests for graphics.GRAPHICS_ALLOCATION
INFO 23 tests run
INFO --- test (4/134) graphics.IMMEDIATE
INFO Begin unit tests for graphics.IMMEDIATE
ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 42, in test_v2f
    self.generic_test('v2f', v2f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 48, in test_v2f_c3f
    self.generic_test('v2f', v2f_data, 'c3f', c3f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 51, in test_v2f_c4f
    self.generic_test('v2f', v2f_data, 'c4f', c4f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 60, in test_v2f_t2f
    self.generic_test('v2f', v2f_data, None, None, 't2f', t2f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 45, in test_v3f
    self.generic_test('v3f', v3f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 54, in test_v3f_c3f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 63, in test_v3f_c3f_t2f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data, 't2f', t2f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 66, in test_v3f_c3f_t3f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data, 't3f', t3f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 57, in test_v3f_c4f
    self.generic_test('v3f', v3f_data, 'c4f', c4f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.IMMEDIATE
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE.py", line 69, in test_v3f_c4f_t4f
    self.generic_test('v3f', v3f_data, 'c4f', c4f_data, 't4f', t4f_data)
  File "tests/../tests/graphics/IMMEDIATE.py", line 35, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

INFO 10 tests run
INFO --- test (5/134) graphics.IMMEDIATE_INDEXED
INFO Begin unit tests for graphics.IMMEDIATE_INDEXED
ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 48, in test_v2f
    self.generic_test('v2f', v2f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 54, in test_v2f_c3f
    self.generic_test('v2f', v2f_data, 'c3f', c3f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 57, in test_v2f_c4f
    self.generic_test('v2f', v2f_data, 'c4f', c4f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 66, in test_v2f_t2f
    self.generic_test('v2f', v2f_data, None, None, 't2f', t2f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 51, in test_v3f
    self.generic_test('v3f', v3f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 60, in test_v3f_c3f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 69, in test_v3f_c3f_t2f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data, 't2f', t2f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 72, in test_v3f_c3f_t3f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data, 't3f', t3f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 63, in test_v3f_c4f
    self.generic_test('v3f', v3f_data, 'c4f', c4f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.IMMEDIATE_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 75, in test_v3f_c4f_t4f
    self.generic_test('v3f', v3f_data, 'c4f', c4f_data, 't4f', t4f_data)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 41, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/IMMEDIATE_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

INFO 10 tests run
INFO --- test (6/134) graphics.RETAINED
INFO Begin unit tests for graphics.RETAINED
ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 43, in test_v2f
    self.generic_test('v2f', v2f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 49, in test_v2f_c3f
    self.generic_test('v2f', v2f_data, 'c3f', c3f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 52, in test_v2f_c4f
    self.generic_test('v2f', v2f_data, 'c4f', c4f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 61, in test_v2f_t2f
    self.generic_test('v2f', v2f_data, None, None, 't2f', t2f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 46, in test_v3f
    self.generic_test('v3f', v3f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 55, in test_v3f_c3f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 64, in test_v3f_c3f_t2f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data, 't2f', t2f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 67, in test_v3f_c3f_t3f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data, 't3f', t3f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 58, in test_v3f_c4f
    self.generic_test('v3f', v3f_data, 'c4f', c4f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

ERROR Failure in graphics.RETAINED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED.py", line 70, in test_v3f_c4f_t4f
    self.generic_test('v3f', v3f_data, 'c4f', c4f_data, 't4f', t4f_data)
  File "tests/../tests/graphics/RETAINED.py", line 36, in generic_test
    self.check(v_data, vertices, n_v)
  File "tests/../tests/graphics/RETAINED.py", line 20, in check
    (e, r))
AssertionError: Feedback array is in error: 0.0, 0.04411765933036804

INFO 10 tests run
INFO --- test (7/134) graphics.RETAINED_INDEXED
INFO Begin unit tests for graphics.RETAINED_INDEXED
ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 49, in test_v2f
    self.generic_test('v2f', v2f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 55, in test_v2f_c3f
    self.generic_test('v2f', v2f_data, 'c3f', c3f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 58, in test_v2f_c4f
    self.generic_test('v2f', v2f_data, 'c4f', c4f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 67, in test_v2f_t2f
    self.generic_test('v2f', v2f_data, None, None, 't2f', t2f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 52, in test_v3f
    self.generic_test('v3f', v3f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 61, in test_v3f_c3f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 70, in test_v3f_c3f_t2f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data, 't2f', t2f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 73, in test_v3f_c3f_t3f
    self.generic_test('v3f', v3f_data, 'c3f', c3f_data, 't3f', t3f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 64, in test_v3f_c4f
    self.generic_test('v3f', v3f_data, 'c4f', c4f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

ERROR Failure in graphics.RETAINED_INDEXED
ERROR Traceback (most recent call last):
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 76, in test_v3f_c4f_t4f
    self.generic_test('v3f', v3f_data, 'c4f', c4f_data, 't4f', t4f_data)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 42, in generic_test
    self.check(get_ordered_data(v_data, n_v), vertices, n_v)
  File "tests/../tests/graphics/RETAINED_INDEXED.py", line 25, in check
    (e, r))
AssertionError: Feedback array is in error: 0.3088235294117647, 0.8823529481887817

INFO 10 tests run
INFO --- test (8/134) graphics.MULTITEXTURE
INFO Begin unit tests for graphics.MULTITEXTURE
INFO 1 tests run
INFO --- test (9/134) window.WINDOW_OPEN
INFO Begin unit tests for window.WINDOW_OPEN
INFO 1 tests run
INFO User marked pass for window.WINDOW_OPEN
INFO --- test (10/134) window.MULTIPLE_WINDOW_OPEN
INFO Begin unit tests for window.MULTIPLE_WINDOW_OPEN
INFO 1 tests run
INFO User marked pass for window.MULTIPLE_WINDOW_OPEN
INFO --- test (11/134) window.CONTEXT_SHARE
INFO Begin unit tests for window.CONTEXT_SHARE
INFO 3 tests run
INFO --- test (12/134) window.WINDOW_SET_VSYNC
INFO Begin unit tests for window.WINDOW_SET_VSYNC
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_VSYNC
INFO --- test (13/134) window.WINDOW_MULTISAMPLE
INFO Begin unit tests for window.WINDOW_MULTISAMPLE
INFO 1 tests run
INFO User marked pass for window.WINDOW_MULTISAMPLE
INFO --- test (14/134) window.WINDOW_STYLE_DIALOG
INFO Begin unit tests for window.WINDOW_STYLE_DIALOG
INFO 1 tests run
ERROR User marked fail for window.WINDOW_STYLE_DIALOG
ERROR Just a square white box with nothing
INFO --- test (15/134) window.WINDOW_STYLE_TOOL
INFO Begin unit tests for window.WINDOW_STYLE_TOOL
INFO 1 tests run
INFO User marked pass for window.WINDOW_STYLE_TOOL
INFO --- test (16/134) window.WINDOW_STYLE_BORDERLESS
INFO Begin unit tests for window.WINDOW_STYLE_BORDERLESS
INFO 1 tests run
INFO User marked pass for window.WINDOW_STYLE_BORDERLESS
INFO --- test (17/134) window.WINDOW_CAPTION
INFO Begin unit tests for window.WINDOW_CAPTION
INFO 1 tests run
INFO User marked pass for window.WINDOW_CAPTION
INFO --- test (18/134) window.WINDOW_SET_ICON
INFO Begin unit tests for window.WINDOW_SET_ICON
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_ICON
INFO --- test (19/134) window.WINDOW_RESIZABLE
INFO Begin unit tests for window.WINDOW_RESIZABLE
INFO 1 tests run
INFO User marked pass for window.WINDOW_RESIZABLE
INFO --- test (20/134) window.WINDOW_SET_SIZE
INFO Begin unit tests for window.WINDOW_SET_SIZE
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_SIZE
INFO --- test (21/134) window.WINDOW_FIXED_SET_SIZE
INFO Begin unit tests for window.WINDOW_FIXED_SET_SIZE
INFO 1 tests run
INFO User marked pass for window.WINDOW_FIXED_SET_SIZE
INFO --- test (22/134) window.WINDOW_SET_MIN_MAX_SIZE
INFO Begin unit tests for window.WINDOW_SET_MIN_MAX_SIZE
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_MIN_MAX_SIZE
INFO --- test (23/134) window.WINDOW_SET_LOCATION
INFO Begin unit tests for window.WINDOW_SET_LOCATION
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_LOCATION
INFO --- test (24/134) window.WINDOW_ACTIVATE
INFO Begin unit tests for window.WINDOW_ACTIVATE
INFO 1 tests run
INFO User marked pass for window.WINDOW_ACTIVATE
INFO --- test (25/134) window.WINDOW_SET_VISIBLE
INFO Begin unit tests for window.WINDOW_SET_VISIBLE
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_VISIBLE
INFO --- test (26/134) window.WINDOW_MINIMIZE_MAXIMIZE
INFO Begin unit tests for window.WINDOW_MINIMIZE_MAXIMIZE
INFO 1 tests run
INFO User marked pass for window.WINDOW_MINIMIZE_MAXIMIZE
INFO --- test (27/134) window.WINDOW_SET_EXCLUSIVE_MOUSE
INFO Begin unit tests for window.WINDOW_SET_EXCLUSIVE_MOUSE
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_EXCLUSIVE_MOUSE
INFO --- test (28/134) window.WINDOW_SET_MOUSE_VISIBLE
INFO Begin unit tests for window.WINDOW_SET_MOUSE_VISIBLE
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_MOUSE_VISIBLE
INFO --- test (29/134) window.WINDOW_SET_MOUSE_CURSOR
INFO Begin unit tests for window.WINDOW_SET_MOUSE_CURSOR
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_MOUSE_CURSOR
INFO --- test (30/134) window.WINDOW_SET_MOUSE_SYSTEM_CURSOR
INFO Begin unit tests for window.WINDOW_SET_MOUSE_SYSTEM_CURSOR
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_MOUSE_SYSTEM_CURSOR
INFO --- test (31/134) window.WINDOW_SET_EXCLUSIVE_KEYBOARD
INFO Begin unit tests for window.WINDOW_SET_EXCLUSIVE_KEYBOARD
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_EXCLUSIVE_KEYBOARD
INFO --- test (32/134) window.WINDOW_INITIAL_FULLSCREEN
INFO Begin unit tests for window.WINDOW_INITIAL_FULLSCREEN
INFO 1 tests run
INFO User marked pass for window.WINDOW_INITIAL_FULLSCREEN
INFO --- test (33/134) window.WINDOW_SET_FULLSCREEN
INFO Begin unit tests for window.WINDOW_SET_FULLSCREEN
INFO 1 tests run
INFO User marked pass for window.WINDOW_SET_FULLSCREEN
INFO --- test (34/134) window.MULTIPLE_SCREEN
INFO Begin unit tests for window.MULTIPLE_SCREEN
INFO 1 tests run
ERROR User marked fail for window.MULTIPLE_SCREEN
ERROR All fullscreens occurred on the primary screen. Logging indicates the following: Python[4706:1307] invalid fullscreen drawable
INFO --- test (35/134) window.MODE_SWITCH
INFO Begin unit tests for window.MODE_SWITCH
INFO 1 tests run
INFO User marked pass for window.MODE_SWITCH
INFO --- test (36/134) window.WINDOW_FULLSCREEN_SIZE
INFO Begin unit tests for window.WINDOW_FULLSCREEN_SIZE
INFO 1 tests run
INFO User marked pass for window.WINDOW_FULLSCREEN_SIZE
INFO --- test (37/134) window.EVENT_KEY
INFO Begin unit tests for window.EVENT_KEY
INFO 1 tests run
INFO User marked pass for window.EVENT_KEY
INFO --- test (38/134) window.EVENT_TEXT
INFO Begin unit tests for window.EVENT_TEXT
INFO 1 tests run
INFO User marked pass for window.EVENT_TEXT
INFO --- test (40/134) window.EVENT_BUTTON
INFO Begin unit tests for window.EVENT_BUTTON
INFO 1 tests run
INFO User marked pass for window.EVENT_BUTTON
INFO --- test (41/134) window.EVENT_MOUSE_MOTION
INFO Begin unit tests for window.EVENT_MOUSE_MOTION
INFO 1 tests run
INFO User marked pass for window.EVENT_MOUSE_MOTION
INFO --- test (42/134) window.EVENT_MOUSE_DRAG
INFO Begin unit tests for window.EVENT_MOUSE_DRAG
INFO 1 tests run
INFO User marked pass for window.EVENT_MOUSE_DRAG
INFO --- test (43/134) window.EVENT_MOUSE_ENTER_LEAVE
INFO Begin unit tests for window.EVENT_MOUSE_ENTER_LEAVE
INFO 1 tests run
INFO User marked pass for window.EVENT_MOUSE_ENTER_LEAVE
INFO --- test (44/134) window.EVENT_MOUSE_SCROLL
